# Generated by Django 5.1.5 on 2026-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_institution_id_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('super_admin', 'Super Admin'), ('it', 'IT')], default='student', max_length=15),
        ),
    ]
