# Generated by Django 5.1.15 on 2026-05-28 16:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyEngagementSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField(db_index=True)),
                ("institution_id", models.UUIDField(db_index=True)),
                (
                    "department",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("batch_id", models.UUIDField(blank=True, null=True)),
                ("practice_attempts", models.PositiveIntegerField(default=0)),
                ("correct_attempts", models.PositiveIntegerField(default=0)),
                ("resource_views", models.PositiveIntegerField(default=0)),
                ("snapshot_date", models.DateField(db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["institution_id", "snapshot_date"],
                        name="des_institution_date_idx",
                    )
                ],
                "unique_together": {("student_id", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="InstitutionSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("institution_id", models.UUIDField(db_index=True)),
                ("total_students", models.PositiveIntegerField(default=0)),
                ("total_active", models.PositiveIntegerField(default=0)),
                ("practice_completion_rate", models.FloatField(default=0.0)),
                ("resource_utilization_rate", models.FloatField(default=0.0)),
                ("snapshot_date", models.DateField(db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["institution_id", "snapshot_date"],
                        name="is_institution_date_idx",
                    )
                ],
                "unique_together": {("institution_id", "snapshot_date")},
            },
        ),
        migrations.CreateModel(
            name="PracticeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField(db_index=True)),
                ("institution_id", models.UUIDField(db_index=True)),
                ("module_id", models.UUIDField()),
                ("question_id", models.UUIDField()),
                ("topic", models.CharField(blank=True, default="", max_length=255)),
                ("difficulty", models.CharField(blank=True, default="", max_length=20)),
                ("is_correct", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["institution_id", "created_at"],
                        name="pe_institution_created_idx",
                    ),
                    models.Index(
                        fields=["student_id", "topic"], name="pe_student_topic_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceViewEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField(db_index=True)),
                ("institution_id", models.UUIDField(db_index=True)),
                ("company_id", models.UUIDField()),
                ("resource_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["institution_id", "company_id"],
                        name="rve_institution_company_idx",
                    )
                ],
            },
        ),
    ]
