# Generated by Django 5.1.15 on 2026-04-12 05:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batches", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("fullname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "college_email_id",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("department", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_profile_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="batches.batch",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "indexes": [
                    models.Index(fields=["student_id"], name="idx_students_student_id"),
                    models.Index(fields=["batch"], name="idx_students_batch_id"),
                    models.Index(fields=["department"], name="idx_students_department"),
                    models.Index(fields=["is_active"], name="idx_students_is_active"),
                ],
            },
        ),
    ]
