# Generated by Django 5.1.5 on 2026-04-21 04:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_scrollconfig_scrollupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resource_modules',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['order'], name='idx_resource_modules_order')],
            },
        ),
    ]
