# Generated by Django 5.1.5 on 2026-04-21 04:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_resource_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcemodule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='students.resourcemodule'),
        ),
        migrations.CreateModel(
            name='ResourceSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='students.resourcemodule')),
            ],
            options={
                'db_table': 'resource_sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image'), ('video_link', 'Video Link'), ('external_link', 'External Link')], max_length=20)),
                ('file_url', models.TextField()),
                ('original_filename', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='students.resourcesection')),
            ],
            options={
                'db_table': 'resource_uploads',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resourcesection',
            index=models.Index(fields=['module'], name='idx_resource_sections_module'),
        ),
        migrations.AddIndex(
            model_name='resourceupload',
            index=models.Index(fields=['resource_section'], name='idx_resource_uploads_section'),
        ),
    ]
