# Generated by Django 5.1.15 on 2026-04-12 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "companies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_published"], name="idx_companies_is_published"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "sections",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("video_link", "Video Link"),
                            ("external_link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.TextField()),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="companies.section",
                    ),
                ),
            ],
            options={
                "db_table": "uploads",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="section",
            index=models.Index(fields=["company"], name="idx_sections_company_id"),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("company", "section_name")},
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(fields=["section"], name="idx_uploads_section_id"),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(fields=["upload_type"], name="idx_uploads_upload_type"),
        ),
    ]
