# Generated by Django 5.1.15 on 2026-05-28 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PracticeQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_number",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("title", models.TextField(blank=True, default="")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("fib", "Fill in the Blank"),
                        ],
                        default="mcq",
                        max_length=10,
                    ),
                ),
                (
                    "mcq_type",
                    models.CharField(
                        choices=[
                            ("single", "Single correct answer"),
                            ("multiple", "Multiple correct answers"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "question_content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text only"),
                            ("image", "Image only"),
                            ("both", "Text and image"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("question_text", models.TextField(blank=True, default="")),
                (
                    "question_image_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "fib_answer",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "explanation_type",
                    models.CharField(
                        choices=[
                            ("none", "No explanation"),
                            ("text", "Text only"),
                            ("image", "Image only"),
                            ("both", "Text and image"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("explanation_text", models.TextField(blank=True, default="")),
                (
                    "explanation_image_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "practice_questions",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "institution_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="practice.practicemodule",
                    ),
                ),
            ],
            options={
                "db_table": "practice_modules",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeQuestionOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=5)),
                ("text", models.TextField(blank=True, default="")),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="practice.practicequestion",
                    ),
                ),
            ],
            options={
                "db_table": "practice_question_options",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "institution_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="practice.practicemodule",
                    ),
                ),
            ],
            options={
                "db_table": "practice_sections",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="practice.practicesection",
            ),
        ),
        migrations.CreateModel(
            name="PracticeQuestionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField(db_index=True)),
                ("selected_option_ids", models.JSONField(default=list)),
                ("is_correct", models.BooleanField()),
                ("attempt_number", models.PositiveIntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_attempts",
                        to="practice.practicequestion",
                    ),
                ),
            ],
            options={
                "db_table": "practice_question_attempts",
                "ordering": ["attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["student_id", "question"],
                        name="idx_pqa_student_question",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PracticeQuestionProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_visited", "Not Visited"),
                            ("visited", "Visited"),
                            ("attempted", "Attempted"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="not_visited",
                        max_length=20,
                    ),
                ),
                ("first_visited_at", models.DateTimeField(blank=True, null=True)),
                ("first_attempted_at", models.DateTimeField(blank=True, null=True)),
                ("first_completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="practice.practicequestion",
                    ),
                ),
            ],
            options={
                "db_table": "practice_question_progress",
                "indexes": [
                    models.Index(
                        fields=["student_id", "question"],
                        name="idx_pqp_student_question",
                    ),
                    models.Index(fields=["student_id"], name="idx_pqp_student_id"),
                ],
                "unique_together": {("student_id", "question")},
            },
        ),
        migrations.AddIndex(
            model_name="practicequestion",
            index=models.Index(
                fields=["section", "is_published"], name="idx_pq_section_published"
            ),
        ),
    ]
