# Generated by Django 5.1.5 on 2026-06-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='practicemodule',
            name='idx_pmodule_inst_published',
        ),
        migrations.RemoveIndex(
            model_name='practicesection',
            name='idx_psection_inst_published',
        ),
        migrations.AddField(
            model_name='practicequestionattempt',
            name='institution_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='practicequestionprogress',
            name='institution_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='practicequestionattempt',
            index=models.Index(fields=['institution_id'], name='idx_pqa_institution_id'),
        ),
        migrations.AddIndex(
            model_name='practicequestionprogress',
            index=models.Index(fields=['institution_id'], name='idx_pqp_institution_id'),
        ),
    ]
