# Generated by Django 5.1.15 on 2026-07-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0005_renumber_questions_per_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicequestion",
            name="explanation_image_size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="practicequestion",
            name="question_image_size_bytes",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
