# Generated by Django 5.1.15 on 2026-05-28 16:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("institution_id", models.UUIDField(db_index=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("resource_upload", "Resource Upload"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_read", "is_deleted"],
                        name="notif_user_read_deleted_idx",
                    ),
                    models.Index(fields=["-created_at"], name="notif_created_desc_idx"),
                ],
            },
        ),
    ]
