# Generated by Django 5.1.5 on 2026-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_question_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicequestion',
            name='question_content_type',
            field=models.CharField(choices=[('text', 'Text only'), ('image', 'Image only'), ('both', 'Text and image')], default='text', help_text='Controls which elements (text / image / both) make up the question body.', max_length=10),
        ),
    ]
