# Generated by Django 5.1.5 on 2026-04-25 05:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_practicequestion_question_content_type'),
        ('students', '0005_resource_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='mcq_type',
            field=models.CharField(choices=[('single', 'Single correct answer'), ('multiple', 'Multiple correct answers')], default='single', help_text='Single or multiple correct answers. Relevant only for MCQ.', max_length=10),
        ),
        migrations.AddField(
            model_name='practicequestionprogress',
            name='first_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='explanation_image_key',
            field=models.CharField(blank=True, default='', help_text='Cloudflare R2 object key for the explanation image.', max_length=500),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='fib_answer',
            field=models.CharField(blank=True, default='', help_text='FIB: the correct answer for the blank.', max_length=500),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='question_text',
            field=models.TextField(blank=True, default='', help_text='Full question text. Use ___ for blanks in FIB.'),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='title',
            field=models.TextField(blank=True, default='', help_text='Short display title / preview'),
        ),
        migrations.AlterField(
            model_name='practicequestionprogress',
            name='status',
            field=models.CharField(choices=[('not_visited', 'Not Visited'), ('visited', 'Visited'), ('attempted', 'Attempted'), ('completed', 'Completed')], db_index=True, default='not_visited', max_length=20),
        ),
        migrations.CreateModel(
            name='PracticeQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='Display letter: A, B, C, D …', max_length=5)),
                ('text', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='practice.practicequestion')),
            ],
            options={
                'db_table': 'practice_question_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_ids', models.JSONField(default=list)),
                ('is_correct', models.BooleanField()),
                ('attempt_number', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempts', to='practice.practicequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='students.student')),
            ],
            options={
                'db_table': 'practice_question_attempts',
                'ordering': ['attempt_number'],
                'indexes': [models.Index(fields=['student', 'question'], name='idx_pqa_student_question')],
            },
        ),
    ]
