# Generated by Django 5.1.5 on 2026-06-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_add_modules'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='idx_companies_created_desc',
        ),
        migrations.RemoveIndex(
            model_name='upload',
            name='idx_uploads_created_desc',
        ),
    ]
