# Generated by Django 5.1.15 on 2026-07-10 06:45

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


def grandfather_existing_uploads_as_clean(apps, schema_editor):
    """
    scan_status is a new gate — student-facing queries now require
    scan_status="clean" to show an upload. Uploads confirmed before this
    migration were already live and already served to students without
    incident; defaulting them to "pending" would make them vanish from
    every student view the moment this migration runs. Grandfather them in
    as "clean" so existing content stays visible; only uploads confirmed
    from this point forward go through the real pending -> scanned gate.
    """
    Upload = apps.get_model("resources", "Upload")
    ModuleUpload = apps.get_model("resources", "ModuleUpload")
    Upload.objects.filter(scan_status="pending").update(scan_status="clean")
    ModuleUpload.objects.filter(scan_status="pending").update(scan_status="clean")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_institution_id_not_null"),
    ]

    operations = [
        # Already applied before django-migration-linter was adopted
        # (2026-09-08) — grandfathered, not a statement that this
        # migration's pattern is safe to repeat. See
        # PRODUCTION_CHECKLIST.md 'Items Added During Development'.
        IgnoreMigration(),
        migrations.AddField(
            model_name="moduleupload",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("clean", "Clean"),
                    ("infected", "Infected"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="upload",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("clean", "Clean"),
                    ("infected", "Infected"),
                    ("error", "Error"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="moduleupload",
            index=models.Index(
                fields=["scan_status"], name="idx_module_uploads_scan_status"
            ),
        ),
        migrations.AddIndex(
            model_name="upload",
            index=models.Index(fields=["scan_status"], name="idx_uploads_scan_status"),
        ),
        migrations.RunPython(grandfather_existing_uploads_as_clean, noop_reverse),
    ]
