# Generated by Django 5.1.5 on 2026-08-11 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Already applied before django-migration-linter was adopted
        # (2026-09-08) — grandfathered, not a statement that this
        # migration's pattern is safe to repeat. See
        # PRODUCTION_CHECKLIST.md 'Items Added During Development'.
        IgnoreMigration(),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_number', models.PositiveIntegerField(db_index=True, default=0)),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice')], default='mcq', max_length=10)),
                ('mcq_type', models.CharField(choices=[('single', 'Single correct answer'), ('multiple', 'Multiple correct answers')], default='single', max_length=10)),
                ('question_content_type', models.CharField(choices=[('text', 'Text only'), ('image', 'Image only'), ('both', 'Text and image')], default='text', max_length=10)),
                ('question_text', models.TextField(blank=True, default='')),
                ('question_image_key', models.CharField(blank=True, default='', max_length=500)),
                ('question_image_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assessment_question_papers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=5)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('image_key', models.CharField(blank=True, default='', max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question')),
            ],
            options={
                'db_table': 'assessment_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='assessments.questionpaper')),
            ],
            options={
                'db_table': 'assessment_question_sets',
                'ordering': ['order'],
                'unique_together': {('paper', 'label')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionset'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['set', 'question_number'], name='idx_aq_set_number'),
        ),
    ]
