# Generated by Django 5.1.5 on 2026-08-11 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('global_start_time', models.DateTimeField(blank=True, null=True)),
                ('global_expire_time', models.DateTimeField()),
                ('exam_duration_minutes', models.PositiveIntegerField()),
                ('pass_cutoff_percentage', models.PositiveIntegerField(default=40)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('CLOSED', 'Closed')], db_index=True, default='SCHEDULED', max_length=10)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assessments.questionpaper')),
            ],
            options={
                'db_table': 'assessment_batch_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='assessments.batchassignment')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='assessments.questionset')),
            ],
            options={
                'db_table': 'assessment_student_set_allocations',
            },
        ),
        migrations.AddIndex(
            model_name='batchassignment',
            index=models.Index(fields=['batch_id'], name='idx_aba_batch_id'),
        ),
        migrations.AddIndex(
            model_name='batchassignment',
            index=models.Index(fields=['status', 'global_expire_time'], name='idx_aba_status_expire'),
        ),
        migrations.AddIndex(
            model_name='studentsetallocation',
            index=models.Index(fields=['assignment', 'student_id'], name='idx_assa_assignment_student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsetallocation',
            unique_together={('assignment', 'student_id')},
        ),
    ]
