# Generated by Django 5.1.5 on 2026-08-11 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_batchassignment_studentsetallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto-submitted'), ('EXPIRED_UNSTARTED', 'Expired without starting')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assessments.batchassignment')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assessments.questionset')),
            ],
            options={
                'db_table': 'assessment_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ResultSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.UUIDField(db_index=True)),
                ('institution_id', models.UUIDField(db_index=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto-submitted'), ('EXPIRED_UNSTARTED', 'Expired without starting')], db_index=True, max_length=20)),
                ('malpractice_flag', models.BooleanField(default=False)),
                ('malpractice_reasons', models.JSONField(blank=True, default=list)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessments.batchassignment')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'assessment_result_summaries',
                'ordering': ['-ended_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['status', 'ends_at'], name='idx_as_status_ends_at'),
        ),
        migrations.AddIndex(
            model_name='resultsummary',
            index=models.Index(fields=['assignment', 'student_id'], name='idx_ars_assignment_student'),
        ),
    ]
