# Generated by Django 5.1.5 on 2026-08-12 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentsession_resultsummary_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentsession',
            unique_together={('assignment', 'student_id')},
        ),
    ]
