# Generated by Django 5.1.5 on 2026-08-12 01:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessmentsession_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_ids', models.JSONField(blank=True, default=list)),
                ('is_correct', models.BooleanField(default=False)),
                ('marks_awarded', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_responses', to='assessments.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'assessment_responses',
                'indexes': [models.Index(fields=['session'], name='idx_ar_session')],
                'unique_together': {('session', 'question')},
            },
        ),
    ]
