# Generated by Django 5.1.5 on 2026-08-12 02:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessmentresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab switch'), ('window_blur', 'Window blur'), ('fullscreen_exit', 'Fullscreen exit'), ('copy', 'Copy'), ('paste', 'Paste'), ('contextmenu', 'Right-click')], db_index=True, max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_logs', to='assessments.assessmentsession')),
            ],
            options={
                'db_table': 'assessment_activity_logs',
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['session', 'event_type'], name='idx_al_session_type')],
            },
        ),
    ]
