# Generated by Django 5.1.5 on 2026-08-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_activitylog'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='resultsummary',
            index=models.Index(fields=['assignment', 'institution_id'], name='idx_ars_assignment_institution'),
        ),
        migrations.AddIndex(
            model_name='resultsummary',
            index=models.Index(fields=['assignment', 'score'], name='idx_ars_assignment_score'),
        ),
    ]
