# Generated by Django 5.1.5 on 2026-08-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_resultsummary_idx_ars_assignment_institution_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assessmentresponse',
            name='idx_ar_session',
        ),
        migrations.RemoveIndex(
            model_name='studentsetallocation',
            name='idx_assa_assignment_student',
        ),
    ]
