# Generated by Django 5.1.5 on 2026-08-12 19:45

import django.db.models.deletion
from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_remove_assessmentresponse_idx_ar_session_and_more'),
    ]

    operations = [
        # Already applied before django-migration-linter was adopted
        # (2026-09-08) — grandfathered, not a statement that this
        # migration's pattern is safe to repeat. See
        # PRODUCTION_CHECKLIST.md 'Items Added During Development'.
        IgnoreMigration(),
        migrations.AlterField(
            model_name='assessmentresponse',
            name='session',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentsession'),
        ),
        migrations.AlterField(
            model_name='studentsetallocation',
            name='assignment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='assessments.batchassignment'),
        ),
    ]
