# Generated by Django 5.1.5 on 2026-08-12 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_remove_assessmentresponse_idx_ar_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresponse',
            name='session',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='assessments.assessmentsession'),
        ),
        migrations.AlterField(
            model_name='studentsetallocation',
            name='assignment',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='assessments.batchassignment'),
        ),
    ]
