# Generated by Django 5.1.5 on 2026-08-12 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_assessmentresponse_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(blank=True, default='', max_length=255)),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessment_failed_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task_name', 'resolved_at'], name='idx_fj_task_resolved')],
            },
        ),
    ]
