# Generated by Django 5.1.5 on 2026-08-14 09:30

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_failedjob'),
    ]

    operations = [
        # Already applied before django-migration-linter was adopted
        # (2026-09-08) — grandfathered, not a statement that this
        # migration's pattern is safe to repeat. See
        # PRODUCTION_CHECKLIST.md 'Items Added During Development'.
        IgnoreMigration(),
        migrations.AddField(
            model_name='questionpaper',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
