# Generated by Django 5.1.5 on 2026-08-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_failedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
