# Generated by Django 5.1.5 on 2026-08-14 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0012_batchassignment_show_result_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='is_published',
        ),
    ]
