# Generated by Django 5.1.5 on 2026-08-15 12:16

from django.db import migrations, models
from django_migration_linter import IgnoreMigration


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_remove_questionpaper_is_published'),
    ]

    operations = [
        # Already applied before django-migration-linter was adopted
        # (2026-09-08) — grandfathered, not a statement that this
        # migration's pattern is safe to repeat. See
        # PRODUCTION_CHECKLIST.md 'Items Added During Development'.
        IgnoreMigration(),
        migrations.AddField(
            model_name='batchassignment',
            name='departments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
