# Generated by Django 5.1.5 on 2026-08-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0013_remove_questionpaper_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchassignment',
            name='departments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
