# Generated by Django 5.1.5 on 2026-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_batchassignment_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab switch'), ('window_blur', 'Window blur'), ('fullscreen_exit', 'Fullscreen exit'), ('copy', 'Copy'), ('paste', 'Paste'), ('contextmenu', 'Right-click'), ('question_answered', 'Answered a question'), ('question_answer_changed', 'Changed an answer'), ('screenshot_attempt', 'Screenshot attempt'), ('connection_lost', 'Lost internet connection'), ('admin_extended_time', 'Admin extended exam time')], db_index=True, max_length=30),
        ),
    ]
