# Generated by Django 5.1.5 on 2026-08-26 21:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_alter_activitylog_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.questionset')),
            ],
            options={
                'db_table': 'assessment_question_sections',
                'ordering': ['order'],
                'unique_together': {('set', 'title')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionsection'),
        ),
    ]
