# Generated by Django 5.1.5 on 2026-08-27 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0019_alter_question_section_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsession',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assessments.batchassignment'),
        ),
        migrations.AlterField(
            model_name='resultsummary',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessments.batchassignment'),
        ),
    ]
