# Generated by Django 5.1.15 on 2026-05-28 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrollConfig",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("left", "Left (RTL marquee)"),
                            ("right", "Right (LTR marquee)"),
                        ],
                        default="left",
                        max_length=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scroll_config",
            },
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_name", models.CharField(max_length=255, unique=True)),
                (
                    "institution_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "batches",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["institution_id"], name="idx_batches_institution_id"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "institution_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="users.resourcemodule",
                    ),
                ),
            ],
            options={
                "db_table": "resource_modules",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="users.resourcemodule",
                    ),
                ),
            ],
            options={
                "db_table": "resource_sections",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "upload_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("video_link", "Video Link"),
                            ("external_link", "External Link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.TextField()),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resource_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="users.resourcesection",
                    ),
                ),
            ],
            options={
                "db_table": "resource_uploads",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrollUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("show_new_badge", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scroll_updates",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(fields=["order"], name="idx_scroll_updates_order")
                ],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True, unique=True)),
                (
                    "student_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "institution_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("fullname", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "college_email_id",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("department", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_profile_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="users.batch",
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="users.student",
                    ),
                ),
            ],
            options={
                "db_table": "student_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="resourcemodule",
            index=models.Index(fields=["order"], name="idx_resource_modules_order"),
        ),
        migrations.AddIndex(
            model_name="resourcemodule",
            index=models.Index(
                fields=["institution_id"], name="idx_resmod_institution_id"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcesection",
            index=models.Index(fields=["module"], name="idx_resource_sections_module"),
        ),
        migrations.AddIndex(
            model_name="resourceupload",
            index=models.Index(
                fields=["resource_section"], name="idx_resource_uploads_section"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["student_id"], name="idx_students_student_id"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["batch"], name="idx_students_batch_id"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["department"], name="idx_students_department"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["is_active"], name="idx_students_is_active"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["institution_id"], name="idx_students_institution_id"
            ),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["is_read"], name="idx_inquiries_is_read"),
        ),
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["student"], name="idx_inquiries_student"),
        ),
    ]
