# Generated by Django 5.1.5 on 2026-06-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_resource_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='student',
            name='idx_students_college_email',
        ),
    ]
