# Generated by Django 5.1.5 on 2026-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_institution_id_scroll_config_update'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scrollupdate',
            name='idx_scroll_updates_order',
        ),
        migrations.AddField(
            model_name='scrollconfig',
            name='institution_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scrollupdate',
            name='institution_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrollconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='scrollupdate',
            index=models.Index(fields=['institution_id', 'order'], name='idx_scroll_updates_inst_order'),
        ),
    ]
